Repository AY2021S2-CS2103T-T10-2/tp, pull requests merged in 2021-03, with the labels that each got.

#26 Update find task command in User guide
  docs/UserGuide.md
Labels: priority.High, type.Task

#27 Update Non-functional requirements in Developer guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#28 Update UG and DG by Han Bin
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#31 Branch update DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#32 Branch update UG
  docs/UserGuide.md
Labels: priority.High, type.Task

#34 Update DG glossary
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#36 Update Config file
  docs/_config.yml
Labels: priority.High, type.Task

#47 Find task(s) by description
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/task/DescriptionContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/task/DescriptionContainsKeywordsPredicateTest.java
Labels: priority.High, type.Story, type.Task

#63 Update DG and Check code quality
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
Labels: type.Task

#71 Fix bug: HBox of tasklist does not grow at some length
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, severity.Medium, type.Bug

#72 Improve Status test coverage
  src/main/java/seedu/address/model/task/Status.java
  src/test/java/seedu/address/model/task/StatusTest.java
Labels: priority.High, type.Task

#69 refactor for SRP
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
Labels: priority.High, type.Enhancement, type.Task

#73 Refactor email to recurring schedule
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Email.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/Title.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCardDetails.java
  src/test/data/JsonPlannerStorageTest/invalidAndValidTaskPlanner.json
  src/test/data/JsonPlannerStorageTest/invalidTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/duplicateTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/invalidTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/typicalTasksPlanner.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteFieldCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/PlannerTest.java
  src/test/java/seedu/address/model/task/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/EmailTest.java
  src/test/java/seedu/address/model/task/RecurringScheduleTest.java
  src/test/java/seedu/address/model/task/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High, type.Task

#74 Update recurring schedule
  docs/images/Ui.png
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/model/task/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/TitleContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/model/task/RecurringScheduleTest.java
Labels: priority.Medium, type.Bug, type.Task

#77 Update constraints for Deadline
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/test/data/JsonSerializablePlannerTest/duplicateTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/typicalTasksPlanner.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteFieldCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#79 Use local date and time
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/StartTime.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCardDetails.java
  src/test/data/JsonSerializablePlannerTest/duplicateTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/invalidTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/typicalTasksPlanner.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteFieldCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#81 Edit help command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
Labels: priority.Medium, severity.VeryLow

#82 Deadline tools
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/StartTime.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.Medium

#83 Implement Countdown
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/parser/CountdownCommandParser.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountdownCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/CountdownCommandParserTest.java
Labels: priority.High, type.Story

#84 Refactor find command and add findCommandParserUtil
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParserUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserUtilTest.java
Labels: priority.Medium, type.Task

#85 Generate weekly biweekly recurring schedule
  src/main/java/seedu/address/model/task/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/ui/TaskCardDetails.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/model/task/RecurringScheduleTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
Labels: priority.High, type.Story, type.Task

#86 Update DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: priority.Medium, type.Task

#87 Make deadline not compulsory
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/ui/TaskCardDetails.java
  src/main/resources/view/TaskListCardDetails.fxml
  src/test/data/JsonPlannerStorageTest/invalidAndValidTaskPlanner.json
  src/test/java/seedu/address/model/task/DeadlineTest.java
Labels: priority.Medium

#88 Update DG for mark done feature
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/DoneSequenceDiagram.puml
  docs/images/DoneSequenceDiagram.png
Labels: priority.High, type.Enhancement

#91 Fix bug in Recurring Schedule, update parts of UG and DG
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonPlannerStorageTest/invalidAndValidTaskPlanner.json
  src/test/data/JsonPlannerStorageTest/invalidTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/duplicateTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/typicalTasksPlanner.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteFieldCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/RecurringScheduleTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High, type.Bug, type.Enhancement, type.Task

#94 Update bug fix deadline recurring schedule
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
Labels: priority.High, type.Bug, type.Task

#95 Refactor of StartTime to duration
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/Duration.java
  src/main/java/seedu/address/model/task/StartTime.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCardDetails.java
  src/main/resources/view/TaskListCardDetails.fxml
  src/test/data/JsonSerializablePlannerTest/duplicateTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/invalidTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/typicalTasksPlanner.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteFieldCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/task/DurationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#96 Update DG and add defensive programming into code
  docs/DeveloperGuide.md
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/FindSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParserUtil.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/RecurringScheduleTest.java
Labels: priority.High, type.Bug, type.Task

#97 Update DG, add logging and assertions
  docs/DeveloperGuide.md
  docs/diagrams/DeleteFieldActivityDiagram.puml
  docs/diagrams/DeleteFieldSequenceDiagram.puml
  docs/images/DeleteFieldActivityDiagram.png
  docs/images/DeleteFieldSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/parser/DeleteFieldCommandParser.java
Labels: priority.High

#100 Fix duration bug update dg diagram size
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/task/Duration.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/task/DurationTest.java
Labels: priority.Medium, type.Bug, type.Task

#101 Make recurring schedule OOP
  src/main/java/seedu/address/model/task/Duration.java
  src/main/java/seedu/address/model/task/RecurringDates.java
  src/main/java/seedu/address/model/task/RecurringDatesUtil.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/test/java/seedu/address/model/task/RecurringDatesUtilTest.java
Labels: priority.Medium, type.Enhancement, type.Task

#102 Create list status task feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/model/task/TaskDoneStatusPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/PlannerParserTest.java
Labels: priority.High

#103 Enforce task conditions
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/conditions/ConditionManager.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Duration.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/data/JsonSerializablePlannerTest/typicalTasksPlanner.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CountdownCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteFieldCommandTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High, type.Task

#104 Modify command words
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High, severity.Medium, type.Enhancement

#105 Add Stats Command
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Planner.java
  src/main/java/seedu/address/model/task/Deadline.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
Labels: priority.High, type.Story

#106 Fix bugs in countdown
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
Labels: priority.High, severity.High, type.Bug

#107 Update ability to delete more fields in DeleteFieldCommand
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
Labels: priority.High, severity.High

#109 Update java docs test cases
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/task/Duration.java
  src/main/java/seedu/address/model/task/RecurringDatesUtil.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDoneStatusPredicate.java
  src/main/java/seedu/address/model/task/predicates/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/predicates/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/predicates/TitleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PlannerParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/task/RecurringDatesUtilTest.java
  src/test/java/seedu/address/model/task/RecurringScheduleTest.java
  src/test/java/seedu/address/model/task/predicates/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TitleContainsKeywordsPredicateTest.java
Labels: priority.High, priority.Medium, type.Bug, type.Task

#110 Enforce task conditions
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/conditions/ConditionManager.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High, type.Enhancement

#111 Deadline tools - Refactor Deadline to Date and remove unwanted logging
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CountdownCommand.java
  src/main/java/seedu/address/logic/commands/DeleteFieldCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewDayCommand.java
  src/main/java/seedu/address/logic/conditions/ConditionManager.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewDayCommandParser.java
  src/main/java/seedu/address/model/task/Date.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDateComparator.java
  src/main/java/seedu/address/model/task/UniqueTaskList.java
  src/main/java/seedu/address/model/task/predicates/TaskDeadlineOnDatePredicate.java
  src/main/java/seedu/address/model/task/predicates/TaskOnDatePredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCardDetails.java
  src/main/resources/view/TaskListCardDetails.fxml
  src/test/data/JsonPlannerStorageTest/invalidAndValidTaskPlanner.json
  src/test/data/JsonPlannerStorageTest/invalidTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/duplicateTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/invalidTaskPlanner.json
  src/test/data/JsonSerializablePlannerTest/typicalTasksPlanner.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CountdownCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ViewDayCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/task/DateTest.java
  src/test/java/seedu/address/model/task/DeadlineTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/model/task/predicates/DescriptionContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TaskDateOnDatePredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TaskDeadlineOnDatePredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TaskOnDatePredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TaskScheduledOnDatePredicateTest.java
  src/test/java/seedu/address/model/task/predicates/TitleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TaskUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#112 Add snooze command
  src/main/java/seedu/address/logic/commands/SnoozeCommand.java
  src/main/java/seedu/address/logic/conditions/ConditionManager.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/PlannerParser.java
  src/main/java/seedu/address/logic/parser/SnoozeCommandParser.java
  src/main/java/seedu/address/model/task/Date.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/model/task/DateTest.java
Labels: priority.High, type.Story, type.Task

#117 Enhance code quality recurring schedule
  build.gradle
  src/main/java/seedu/address/model/task/RecurringDates.java
  src/main/java/seedu/address/model/task/RecurringDatesUtil.java
  src/main/java/seedu/address/model/task/RecurringSchedule.java
  src/test/java/seedu/address/model/task/RecurringDatesUtilTest.java
  src/test/java/seedu/address/model/task/RecurringScheduleTest.java
Labels: priority.Medium, type.Enhancement, type.Task

#119 UG changes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.Low

#120 Update User Guide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#121 Add snooze command Tests
  src/main/java/seedu/address/logic/commands/SnoozeCommand.java
  src/main/java/seedu/address/logic/parser/SnoozeCommandParser.java
  src/test/java/seedu/address/logic/commands/SnoozeCommandTest.java
  src/test/java/seedu/address/logic/parser/SnoozeCommandParserTest.java
Labels: priority.Medium, type.Task

#122 Modify sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium, type.Task

#123 Update UI.png
  docs/images/Ui.png
Labels: priority.High, type.Task
